# Use `../../tools/bin/gen-settings` to create `settings.json`.
---
{
    "minifso": "dev",
    "public": {
        "tests": {
            "passwords": {
                "user": "{{ password }}"
            }
        }
    }
}
---
id: password
q: 'Password that will be used for the a local testing user:'
