#!/bin/sh
set -o errexit -o nounset -o pipefail -o noglob

bucket='noglocal'

echo "Begin setup of bucket '${bucket}'."
sleep 1

set -x
until \
    aws --endpoint-url ${AWS_ENDPOINT_URL} \
        s3api head-bucket --bucket ${bucket}
do
    aws --endpoint-url ${AWS_ENDPOINT_URL} \
        s3api create-bucket --bucket ${bucket}
    sleep 2
done

echo "Configured bucket '${bucket}'."

echo 'Completed Minio setup.  Exiting.'
