#!/usr/bin/env python3

from copy import copy, deepcopy
from datetime import datetime
from io import StringIO
import json
import nog
import os
import os.path
import random
import string
import sys

xout = StringIO()


def printmsg(*args):
    print(*args, file=xout)
    print(*args)


def main():
    if len(sys.argv) != 3:
        raise RuntimeError('Invalid number of args.')
    if sys.argv[1] != '--params':
        raise RuntimeError('Invalid arguments.')
    params = json.loads(sys.argv[2])
    printmsg('params', stringify_pretty(params))

    workspace = nog.openRepo(params['nog']['workspaceRepo'])
    master = workspace.getMaster()
    root = master.tree

    # The program should perhaps not access the job but only print a log to
    # stdout, which the executor attaches to the job.  But without executor, it
    # seems useful to have the main computation and the logging in a single
    # script.
    job = findJob(root, params['nog']['job'])
    printmsg('job', job.sha1, stringify_pretty(job.content))

    prg = findProgram(root, params['nog']['program'])
    printmsg('program', prg.sha1, stringify_pretty(prg.content))

    datalist = versionsHead(next(root.trees('datalist')))
    try:
        results = next(root.trees('results'))
    except StopIteration:
        results = nog.Tree()
        results.name = 'results'
        root.append(results)

    workspace.prefetchBlobs(
            versionsHead(d).blob for d in datalist.entries())
    res = computeAll(datalist, params)
    programs = nog.Tree()
    programs.name = 'programs'
    programs.append(prg)
    res.append(programs)
    replaceEntry(results, res)

    try:
        log = next(root.trees('log'))
        addLogEntry(
                log, auto=True,
                description='Completed job ' + job.meta['job']['id'],
                content='Completed celltracking job.'
            )
    except StopIteration:
        pass

    completeJob(job)

    master = workspace.commitTree(
            subject='Add results for job ' + params['nog']['job']['id'],
            tree=root, parent=master.sha1
        )
    printmsg(master.sha1, stringify_pretty(master.content))


def replaceEntry(tree, child):
    try:
        (idx, e) = next(tree.enumerateEntries(child.name))
        tree.pop(idx)
    except StopIteration:
        idx = 0
    tree.insert(idx, child)


def findProgram(root, sel):
    programs = next(root.trees('programs'))
    pkg = None
    for p in programs.entries():
        if p.meta['package']['name'] == sel['name']:
            pkg = p
            break
    if not pkg:
        raise KeyError('Failed to find program package.')
    prg = None
    for p in pkg.entries():
        if p.sha1 == sel['sha1']:
            prg = p
            break
    if not prg:
        raise KeyError('Failed to find program version (sha1).')
    return prg


# An alternative would be to store stdout and so on in a blob to avoid less
# important content in mongo.
def completeJob(job):
    job.meta['job']['status'] = 'completed'
    stdout = nog.Object()
    stdout.name = 'stdout'
    stdout.meta['description'] = 'stdout of job execution'
    stdout.meta['content'] = xout.getvalue()
    job.insert(0, stdout)


def addLogEntry(log, description, content, auto=None):
    auto = auto or True
    if auto:
        creation = 'automatic'
    else:
        creation = 'human'
    date = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
    entry = nog.Object()
    entry.name = date + '.md'
    entry.meta['logentry'] = {
        'date': date,
        'creation': creation
    }
    entry.meta['description'] = description
    entry.meta['content'] = content
    log.insert(0, entry)


def findJob(tree, job):
    jobs = next(tree.trees('jobs'))
    j = next(jobs.trees(job['id']))
    if j.sha1 != job['sha1']:
        raise RuntimeError('job sha1 mismatch.')
    return j


def computeAll(datalist, params):
    results = nog.Tree()
    results.name = os.path.basename(params['nog']['program']['name'])

    summary = nog.Object()
    results.append(summary)
    summary.name = 'summary.md'
    sumd = '# Summary Report\n\n'

    for d in datalist.entries():
        d = versionsHead(d)
        name = d.name
        specimen = d.meta['specimen']
        sumd = sumd + (' - [specimen {0}]({0}): {1}\n'.format(specimen, name))

        restree = nog.Tree()
        restree.name = specimen
        restree.meta['specimen'] = specimen

        report = nog.Object()
        report.name = 'report.md'
        report.meta['content'] = '# Report {0}\n\n'.format(specimen)
        restree.append(report)

        ts = nog.Tree()
        ts.name = 'input-timeseries'
        ts.meta['specimen'] = specimen
        ts.append(d)
        restree.append(ts)

        printmsg('Fake processing {0}...'.format(name))
        tmpfile = 'tmpfile'
        d.linkBlob(tmpfile)
        with open(tmpfile, 'rb') as fp:
            dat = fp.read()
        os.remove(tmpfile)

        res = nog.Object()
        res.meta['specimen'] = specimen
        res.name = 'tracking-result-' + specimen + '.csv'
        restree.append(res)

        results.append(restree)

    summary.meta['content'] = sumd
    return results


def versionsHead(entry):
    if 'versions' in entry.meta:
        return next(entry.entries())
    else:
        return entry


def stringify_pretty(d):
    return json.dumps(d, sort_keys=True, ensure_ascii=False, indent=2) + '\n'


main()
